version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: my_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: Openeyes088!
      MYSQL_DATABASE: soignemoi_spn
      MYSQL_USER: root
      MYSQL_PASSWORD: Openeyes088!
    ports:
      - "3306:3306"
