version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password_value
      MYSQL_DATABASE: soignemoi_spn
      MYSQL_USER: soignemoi_user
      MYSQL_PASSWORD: user_password_value
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
