app = "soignemoi-spn"
primary_region = "cdg"

[build]
  dockerfile = "./Dockerfile"

[env]
  PORT = "80"

[http_service]
  internal_port = 80
  force_https = true

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

# Service pour MySQL (interne uniquement)
[[services]]
  protocol = "tcp"
  internal_port = 3306
  # Ne définissez pas de "processes" ici, l'image MySQL gère son démarrage.
  internal = true  # Marque ce service comme interne
  [[services.ports]]
    port = 3306
    handlers = ["proxy_proto"]  # ou "tcp" selon les recommandations Fly.io
  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80
  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0

# --- Montage de volume (pour la persistance des données) ---
[[mounts]]
  source = "soignemoi_data"
  destination = "/data"

[metrics]
  port = 9090
  path = "/metrics"

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 1
